name: Build Sass

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ts:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile Sass
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        cache: 'npm'
    - run: npm ci
    - run: npx sass src/scss:build/site/css
