name: Build

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Create .env
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  envkey_VITE_GH_TOKEN: ${{ secrets.VITE_GH_TOKEN }}
            - name: Install packages
              run: yarn install
            - name: Build site
              run: yarn build
