name: Build

on:
  push:
    branches: [ main, vue ]
  pull_request:
    branches: [ main, vue ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test deploy task
      run: chmod -R +x ./scripts/deploy.sh && ./scripts/deploy.sh