name: Build

on:
  push:
    branches: [ main, vue ]
  pull_request:
    branches: [ main, vue ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: yarn install deps
      run: yarn install --frozen-lockfile
    - name: build
      run: chmod +x ./build.sh && ./build.sh