name: Build

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Create env file
              run: "VITE_GH_TOKEN=${{ env.VITE_GH_TOKEN }}" \> .env
            - name: Install packages
              run: yarn install
            - name: Build site
              run: yarn build
